spring:
  profiles:
    active: common # 현재 프로필 설정
    group: # 특정 프로필을 실행할때, 같이 실행되게끔 그룹 짓기
      common: secret # common이 실행되면. secret 프로필 설정
server:
  address: 127.0.0.1

logging:
  level:
    com.xmpy.demo.mapper: TRACE
---

spring:
  config:
    activate:
      on-profile: common

  application:
    name: spring-boot-study
# xmpy-mall 서버 연결 완료

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmpy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sndwod1874*

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xmpy.demo.entity
  configuration:
    map-underscore-to-camel-case: true
# mapper 연결 완료

---

spring:
  config:
    activate:
      on-profile: secret

jwt:
  secret: "6Y9tMfkTPJPDQCCNJDRCaohhhCSQA3wONNmeC7pN9lISm3H4KBpid9HyF5opwPxjQbXgmzj4V0h3cH0X0ldrMg=="
  access-expire-millis: 900000
  refresh-expire-millis: 86400000